[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[project]
dependencies = [
  "PyYAML >= 5.4.1",
]
description = "Runs linting on flux manifests to ensure naming style"
name = "manifest_lint"
requires-python = ">=3.8"
version = "0.1.0"
